"""Create FundTransaction model and update relationships

Revision ID: 0f5bcaada4a6
Revises: 94864d7b4d89
Create Date: 2025-01-17 10:21:00.540882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f5bcaada4a6'
down_revision: Union[str, None] = '94864d7b4d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
