"""optional owner identification_number

Revision ID: 12955d39dab6
Revises: 4f466386dafd
Create Date: 2025-01-20 16:40:44.155727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12955d39dab6'
down_revision: Union[str, None] = '4f466386dafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'identification_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'identification_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
