"""Add costs relationship to Building model

Revision ID: 1919e7c4e35f
Revises: aaa83521e3f7
Create Date: 2025-01-17 09:42:54.420031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1919e7c4e35f'
down_revision: Union[str, None] = 'aaa83521e3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
