"""Add fund_transactions relationship to Cost model

Revision ID: 265ea5eef71b
Revises: 4eca71cf6b5e
Create Date: 2025-01-17 09:34:04.239176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '265ea5eef71b'
down_revision: Union[str, None] = '4eca71cf6b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
