"""Add charges relationship to Building model

Revision ID: 4eca71cf6b5e
Revises: 97d0506dd320
Create Date: 2025-01-17 09:28:27.475696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4eca71cf6b5e'
down_revision: Union[str, None] = '97d0506dd320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
