"""Create FundTransaction model and update relationships

Revision ID: 54dc30eebedf
Revises: 1bb656efb0ff
Create Date: 2025-01-17 10:28:41.693808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54dc30eebedf'
down_revision: Union[str, None] = '1bb656efb0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
