"""Add fund_transactions relationship to Cost model

Revision ID: 9514ffad2eea
Revises: 265ea5eef71b
Create Date: 2025-01-17 09:36:42.556960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9514ffad2eea'
down_revision: Union[str, None] = '265ea5eef71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
