"""Add foreign key relationships

Revision ID: 97d0506dd320
Revises: 2217bbe271c5
Create Date: 2025-01-17 09:22:22.374123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97d0506dd320'
down_revision: Union[str, None] = '2217bbe271c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'units', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_column('units', 'owner_id')
    # ### end Alembic commands ###
